metricbeat.modules:
- module: system
  metricsets:
    # CPU stats
    - cpu
    # System Load stats
    - load
    # Per CPU core stats
    #- core
    # IO stats
    - diskio
    # Per filesystem stats
    - filesystem
    # File system summary stats
    - fsstat
    # Memory stats
    - memory
    # Network stats
    - network
    # Per process stats
    - process
    # Sockets and connection info (linux only)
    #- socket
  enabled: true
  period: 10s
  processes: ['.*']

# In order to capture short lived connections, use a shorter period for system/sockets.
- module: system
  metricsets: [socket]
  period: 500ms
  socket.reverse_lookup.enabled: true

- module: system
  period: 60s
  metricsets: [filesystem, fsstat]
  filters:
    - drop_event.when.regexp.mount_point: '^(/hostfs)?/(sys|cgroup|proc|dev|etc|host|var/lib/docker)($|/)'

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

processors:
- add_cloud_metadata:
output.elasticsearch:
  hosts: ['localhost:9200']
  username: elastic
  password: changeme
